using Gcode.Utils.Entity.Base;

namespace Gcode.Utils.Entity.Slicer
{
	/// <summary>
	/// Gcode, generated by Kisslicer information.
	/// </summary>
	public class KisSlicerInfo: SlicerInfoBase
	{
	}
}
