using System;
using System.Linq;
using Gcode.Utils.Entity;

namespace Gcode.Utils.SlicerParser
{
	public class Slic3RParser: SlicerParserBase<Slic3RInfo>
	{
		public override Slic3RInfo GetSlicerInfo(string[] fileContent)
		{
			var name = fileContent.FirstOrDefault(x => x.StartsWith("; generated by Slic3r "));

			if (name?.Split(' ')[3] == null)
			{
				return null;
			}

			var res = new Slic3RInfo
			{
				Name = name.Split(' ')[3],
				Version = name.Split(' ')[4],
				// no edition provided by Slic3r
				Edition = string.Empty,
			};

			var filamentUsed = fileContent.Where(x => x.StartsWith("; filament used")).ToArray();
			if (filamentUsed.Length == 1 && filamentUsed[0] != null)
			{
				// filament used
				res.FilamentUsedExtruder1 = Convert.ToDecimal(filamentUsed[0].Split('=')[1]?.Split(' ')[1]?.Replace("mm", "").Replace(".", ","));
			}

			if (filamentUsed.Length == 2 && filamentUsed[1] != null)
			{
				// filament used
				res.FilamentUsedExtruder2 = Convert.ToDecimal(filamentUsed[1].Split('=')[1]?.Split(' ')[1]?.Replace("mm", "").Replace(".", ","));
			}
			return res;
		}
	}
}
